namespace AppBridge.ControlPlane.Domain.Common;

/// <summary>
/// Base for mutable entities. Carries the full audit set from ADR-0011 §5: created/updated/deleted
/// by whom and when, plus an optimistic-concurrency token. Trail tables do NOT derive from this —
/// see <see cref="AppendOnlyEntity"/> and the comment there for why.
/// </summary>
public abstract class AuditedEntity
{
    /// <summary>UUID v7, generated by the application (ADR-0011 §1) — never by the database.</summary>
    public Guid Id { get; init; } = Guid.CreateVersion7();

    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>Acting principal's id. Nullable: bootstrap/seed rows have no acting user yet.</summary>
    public Guid? CreatedBy { get; init; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Optimistic concurrency token, mapped to PostgreSQL's <c>xmin</c> system column rather than a
    /// hand-rolled counter (Infrastructure/Configurations sets this up) — one less place for the
    /// increment logic to be wrong.
    /// </summary>
    public uint RowVersion { get; set; }

    /// <summary>Logical deletion (ADR-0011 §3). Tenant data is never physically deleted.</summary>
    public DateTimeOffset? DeletedAt { get; set; }

    public Guid? DeletedBy { get; set; }
}
