// <auto-generated />
using System;
using System.Text.Json;
using AppBridge.ControlPlane.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppBridge.ControlPlane.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925020208_TenantIsolationAndCompositeForeignKeys")]
    partial class TenantIsolationAndCompositeForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.AccessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ip");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workstation_name");

                    b.HasKey("Id")
                        .HasName("pk_access_event");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_access_event_tenant_id_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_access_event_tenant_occurred_at");

                    b.HasIndex("TenantId", "UserAccountId");

                    b.ToTable("access_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_event_event_type_valid", "event_type IN ('authentication', 'logout', 'session_started', 'session_ended')");

                            t.HasCheckConstraint("ck_access_event_result_valid", "result IN ('success', 'failure')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.AppGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ExternalGroupId")
                        .HasColumnType("text")
                        .HasColumnName("external_group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_group_tenant_id_id");

                    b.ToTable("group", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_source_valid", "source IN ('directory', 'local')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.ApplicationPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_application_permission");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_application_permission_tenant_id_id");

                    b.HasIndex("TenantId", "GrantedBy");

                    b.HasIndex("TenantId", "GroupId");

                    b.HasIndex("TenantId", "RevokedBy");

                    b.HasIndex("TenantId", "ApplicationId", "GroupId")
                        .HasDatabaseName("ix_permission_active")
                        .HasFilter("effective_to IS NULL");

                    b.ToTable("application_permission", (string)null);
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.HostPool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackendType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backend_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_host_pool");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_host_pool_tenant_id_id");

                    b.ToTable("host_pool", null, t =>
                        {
                            t.HasCheckConstraint("ck_host_pool_backend_type_valid", "backend_type IN ('rds', 'avd')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.Launch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DenialReason")
                        .HasColumnType("text")
                        .HasColumnName("denial_reason");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("RdpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rdp_expires_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ip");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workstation_name");

                    b.HasKey("Id")
                        .HasName("pk_launch");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_launch_tenant_id_id");

                    b.HasIndex("TenantId", "ApplicationId");

                    b.HasIndex("TenantId", "RequestedAt")
                        .HasDatabaseName("ix_launch_tenant_requested_at");

                    b.HasIndex("TenantId", "SessionId");

                    b.HasIndex("TenantId", "UserAccountId");

                    b.ToTable("launch", null, t =>
                        {
                            t.HasCheckConstraint("ck_launch_outcome_valid", "outcome IN ('granted', 'denied_permission', 'denied_quota', 'denied_host_unavailable', 'error_signing', 'error_internal')");

                            t.HasCheckConstraint("ck_launch_purpose_valid", "purpose IN ('user_initiated', 'prelaunch')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.PurgeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CutoffDate")
                        .HasColumnType("date")
                        .HasColumnName("cutoff_date");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<long>("RowsDeleted")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_deleted");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_purge_run");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_purge_run_tenant_id_id");

                    b.ToTable("purge_run", null, t =>
                        {
                            t.HasCheckConstraint("ck_purge_run_category_valid", "category IN ('access', 'administrative', 'certificate_usage')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RedirectionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAudioIn")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_audio_in");

                    b.Property<bool>("AllowAudioOut")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_audio_out");

                    b.Property<bool>("AllowClipboard")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_clipboard");

                    b.Property<bool>("AllowDrives")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_drives");

                    b.Property<bool>("AllowOtherUsb")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_other_usb");

                    b.Property<bool>("AllowPrinter")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_printer");

                    b.Property<bool>("AllowSerialPorts")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_serial_ports");

                    b.Property<bool>("AllowSmartcard")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_smartcard");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ExceptionReason")
                        .HasColumnType("text")
                        .HasColumnName("exception_reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_redirection_policy");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_redirection_policy_tenant_id_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("uq_redirection_policy_tenant_default")
                        .HasFilter("application_id IS NULL");

                    b.HasIndex("TenantId", "ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("uq_redirection_policy_tenant_application")
                        .HasFilter("application_id IS NOT NULL");

                    b.ToTable("redirection_policy", (string)null);
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RemoteApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ConcurrentLimit")
                        .HasColumnType("integer")
                        .HasColumnName("concurrent_limit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("HostPoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_pool_id");

                    b.Property<string>("IconRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_ref");

                    b.Property<string>("LaunchMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("launch_mode");

                    b.Property<string>("LicenseNotes")
                        .HasColumnType("text")
                        .HasColumnName("license_notes");

                    b.Property<string>("RemoteAppAlias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_app_alias");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_application");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_application_tenant_id_id");

                    b.HasIndex("TenantId", "HostPoolId");

                    b.HasIndex("TenantId", "RemoteAppAlias", "HostPoolId")
                        .IsUnique()
                        .HasDatabaseName("uq_application_tenant_remote_app_alias_host_pool");

                    b.ToTable("application", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_launch_mode_valid", "launch_mode IN ('remote_app', 'confined_desktop')");

                            t.HasCheckConstraint("ck_application_status_valid", "status IN ('draft', 'published', 'retired')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RemoteSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackendSessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backend_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("EndReason")
                        .HasColumnType("text")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("SessionHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_host_id");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ip");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workstation_name");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_session_tenant_id_id");

                    b.HasIndex("TenantId", "SessionHostId")
                        .HasDatabaseName("ix_session_active")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("TenantId", "UserAccountId");

                    b.ToTable("session", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_end_reason_valid", "end_reason IS NULL OR end_reason IN ('logoff', 'disconnect_timeout', 'terminated_by_admin', 'revoked', 'reconciled_missing', 'stale_expired')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("RetentionMonths")
                        .HasColumnType("integer")
                        .HasColumnName("retention_months");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_retention_policy");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_retention_policy_tenant_id_id");

                    b.HasIndex("TenantId", "Category")
                        .IsUnique()
                        .HasDatabaseName("uq_retention_policy_tenant_id_category");

                    b.ToTable("retention_policy", null, t =>
                        {
                            t.HasCheckConstraint("ck_retention_policy_category_valid", "category IN ('access', 'administrative', 'certificate_usage')");

                            t.HasCheckConstraint("ck_retention_policy_months_minimum", "(category = 'access' AND retention_months BETWEEN 6 AND 60) OR (category = 'administrative' AND retention_months BETWEEN 12 AND 60) OR (category = 'certificate_usage' AND retention_months >= 60)");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.SessionHost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fqdn");

                    b.Property<Guid>("HostPoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_pool_id");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<int>("MaxSessions")
                        .HasColumnType("integer")
                        .HasColumnName("max_sessions");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_session_host");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_session_host_tenant_id_id");

                    b.HasIndex("TenantId", "HostPoolId");

                    b.ToTable("session_host", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_host_status_valid", "status IN ('online', 'draining', 'offline')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.SigningCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbprint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_signing_certificate");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_signing_certificate_tenant_id_id");

                    b.HasIndex("Thumbprint")
                        .IsUnique()
                        .HasDatabaseName("uq_signing_certificate_thumbprint");

                    b.ToTable("signing_certificate", null, t =>
                        {
                            t.HasCheckConstraint("ck_signing_certificate_status_valid", "status IN ('active', 'superseded', 'revoked')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdDomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad_domain");

                    b.Property<string>("AdOuDn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad_ou_dn");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_tenant_slug");

                    b.ToTable("tenant", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_status_valid", "status IN ('active', 'suspended', 'terminated')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdObjectSid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad_object_sid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Upn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upn");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_user_account_tenant_id_id");

                    b.HasIndex("TenantId", "AdObjectSid")
                        .IsUnique()
                        .HasDatabaseName("uq_user_account_tenant_ad_object_sid");

                    b.HasIndex("TenantId", "ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("uq_user_account_tenant_external_subject");

                    b.ToTable("user_account", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_account_status_valid", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.UserGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_user_group_membership");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("uq_user_group_membership_tenant_id_id");

                    b.HasIndex("TenantId", "GroupId");

                    b.HasIndex("TenantId", "UserAccountId");

                    b.ToTable("user_group_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_group_membership_source_valid", "source IN ('directory', 'local')");
                        });
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.AccessEvent", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_event_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserAccountId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_event_user_account");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.AppGroup", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_tenant");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.ApplicationPermission", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_permission_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.RemoteApplication", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ApplicationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_permission_application");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GrantedBy")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_permission_granted_by");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.AppGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_permission_group");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RevokedBy")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_application_permission_revoked_by");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.HostPool", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_host_pool_tenant");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.Launch", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_launch_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.RemoteApplication", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ApplicationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_launch_application");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.RemoteSession", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SessionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_launch_session");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserAccountId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_launch_user_account");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.PurgeRun", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purge_run_tenant");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RedirectionPolicy", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_redirection_policy_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.RemoteApplication", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ApplicationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_redirection_policy_application");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RemoteApplication", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.HostPool", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "HostPoolId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_host_pool");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RemoteSession", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.SessionHost", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SessionHostId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_session_host");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserAccountId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_account");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.RetentionPolicy", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retention_policy_tenant");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.SessionHost", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_host_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.HostPool", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "HostPoolId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_host_host_pool");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.SigningCertificate", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_signing_certificate_tenant");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_account_tenant");
                });

            modelBuilder.Entity("AppBridge.ControlPlane.Domain.Entities.UserGroupMembership", b =>
                {
                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_membership_tenant");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.AppGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_membership_group");

                    b.HasOne("AppBridge.ControlPlane.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserAccountId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_membership_user_account");
                });
#pragma warning restore 612, 618
        }
    }
}
